### ISSUE TITLE
Error 413 Payload Too Large

### ISSUE THREAD

**Issue by davidak** [yk/litter#4]
When i try to upload a Jpeg bigger than 3MB, the UI does nothing. The Browser Network tab shows an error response.

It would be good to clarify the allowed size and maybe handle this case. Minimal would be to put text "max. X MB" in the file select button. You could also create a dialog with the error.

Tested:

13.3MB - 413 Payload Too Large (Vercel Error: FUNCTION_PAYLOAD_TOO_LARGE)
7.80MB - 413 Payload Too Large (Vercel Error: FUNCTION_PAYLOAD_TOO_LARGE)
4.22MB - 413 Payload Too Large (Vercel Error: FUNCTION_PAYLOAD_TOO_LARGE)
2.87MB - 405 Method Not Allowed
2.75MB - 400 Bad Request
2.14MB - 405 Method Not Allowed
1.51MB - 504 Gateway Timeout (FUNCTION_INVOCATION_TIMEOUT)
1.31MB - 504 Gateway Timeout (FUNCTION_INVOCATION_TIMEOUT)
0.79MB - 200 OK

```
Anfrage-URL: https://litter.ykilcher.com/api/posts
Anfragemethode: POST
Statuscode: 413 Payload Too Large
```

```
Date: Fri, 05 Jan 2024 12:48:51 GMT
Server: Vercel
Strict-Transport-Security: max-age=63072000

X-Matched-Path: /api/posts
X-Vercel-Error: FUNCTION_PAYLOAD_TOO_LARGE
X-Vercel-Id: fra1::6xrvb-1704458916273-96897f275fd9
```

**Comment by yk** [comment]
thank you for the error reports and suggestions, but this is not a real social network and I will take it down very soon, so I will not put effort into fixing many things :)
